// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package rightmove

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DetailedDescription struct {
	Bedrooms             int32    `protobuf:"varint,1,opt,name=Bedrooms,json=bedrooms,proto3" json:"Bedrooms,omitempty"`
	Summary              string   `protobuf:"bytes,2,opt,name=Summary,json=summary,proto3" json:"Summary,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailedDescription) Reset()         { *m = DetailedDescription{} }
func (m *DetailedDescription) String() string { return proto.CompactTextString(m) }
func (*DetailedDescription) ProtoMessage()    {}
func (*DetailedDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *DetailedDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailedDescription.Unmarshal(m, b)
}
func (m *DetailedDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailedDescription.Marshal(b, m, deterministic)
}
func (m *DetailedDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailedDescription.Merge(m, src)
}
func (m *DetailedDescription) XXX_Size() int {
	return xxx_messageInfo_DetailedDescription.Size(m)
}
func (m *DetailedDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailedDescription.DiscardUnknown(m)
}

var xxx_messageInfo_DetailedDescription proto.InternalMessageInfo

func (m *DetailedDescription) GetBedrooms() int32 {
	if m != nil {
		return m.Bedrooms
	}
	return 0
}

func (m *DetailedDescription) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *DetailedDescription) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Media struct {
	MediaType            int32    `protobuf:"varint,1,opt,name=MediaType,json=mediaType,proto3" json:"MediaType,omitempty"`
	MediaURL             string   `protobuf:"bytes,2,opt,name=MediaURL,json=mediaURL,proto3" json:"MediaURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Media) Reset()         { *m = Media{} }
func (m *Media) String() string { return proto.CompactTextString(m) }
func (*Media) ProtoMessage()    {}
func (*Media) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Media) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Media.Unmarshal(m, b)
}
func (m *Media) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Media.Marshal(b, m, deterministic)
}
func (m *Media) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Media.Merge(m, src)
}
func (m *Media) XXX_Size() int {
	return xxx_messageInfo_Media.Size(m)
}
func (m *Media) XXX_DiscardUnknown() {
	xxx_messageInfo_Media.DiscardUnknown(m)
}

var xxx_messageInfo_Media proto.InternalMessageInfo

func (m *Media) GetMediaType() int32 {
	if m != nil {
		return m.MediaType
	}
	return 0
}

func (m *Media) GetMediaURL() string {
	if m != nil {
		return m.MediaURL
	}
	return ""
}

type Coordinates struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=Latitude,json=latitude,proto3" json:"Latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=Longitude,json=longitude,proto3" json:"Longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinates) Reset()         { *m = Coordinates{} }
func (m *Coordinates) String() string { return proto.CompactTextString(m) }
func (*Coordinates) ProtoMessage()    {}
func (*Coordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Coordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinates.Unmarshal(m, b)
}
func (m *Coordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinates.Marshal(b, m, deterministic)
}
func (m *Coordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinates.Merge(m, src)
}
func (m *Coordinates) XXX_Size() int {
	return xxx_messageInfo_Coordinates.Size(m)
}
func (m *Coordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinates.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinates proto.InternalMessageInfo

func (m *Coordinates) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Coordinates) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Location struct {
	CountryCode          string       `protobuf:"bytes,1,opt,name=CountryCode,json=countryCode,proto3" json:"CountryCode,omitempty"`
	PostalCode           string       `protobuf:"bytes,2,opt,name=PostalCode,json=postalCode,proto3" json:"PostalCode,omitempty"`
	PropertyNumberOrName string       `protobuf:"bytes,3,opt,name=PropertyNumberOrName,json=propertyNumberOrName,proto3" json:"PropertyNumberOrName,omitempty"`
	StreetName           string       `protobuf:"bytes,4,opt,name=StreetName,json=streetName,proto3" json:"StreetName,omitempty"`
	TownOrCity           string       `protobuf:"bytes,5,opt,name=TownOrCity,json=townOrCity,proto3" json:"TownOrCity,omitempty"`
	Coordinates          *Coordinates `protobuf:"bytes,6,opt,name=Coordinates,json=coordinates,proto3" json:"Coordinates,omitempty"`
	Address              string       `protobuf:"bytes,7,opt,name=Address,json=address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *Location) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *Location) GetPropertyNumberOrName() string {
	if m != nil {
		return m.PropertyNumberOrName
	}
	return ""
}

func (m *Location) GetStreetName() string {
	if m != nil {
		return m.StreetName
	}
	return ""
}

func (m *Location) GetTownOrCity() string {
	if m != nil {
		return m.TownOrCity
	}
	return ""
}

func (m *Location) GetCoordinates() *Coordinates {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *Location) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ListingUpdateRequest struct {
	NetworkID            int64                `protobuf:"varint,1,opt,name=NetworkID,json=networkID,proto3" json:"NetworkID,omitempty"`
	BranchID             int64                `protobuf:"varint,2,opt,name=BranchID,json=branchID,proto3" json:"BranchID,omitempty"`
	AgentRef             string               `protobuf:"bytes,3,opt,name=AgentRef,json=agentRef,proto3" json:"AgentRef,omitempty"`
	Published            bool                 `protobuf:"varint,4,opt,name=Published,json=published,proto3" json:"Published,omitempty"`
	PropertyType         int32                `protobuf:"varint,5,opt,name=PropertyType,json=propertyType,proto3" json:"PropertyType,omitempty"`
	Status               int32                `protobuf:"varint,6,opt,name=Status,json=status,proto3" json:"Status,omitempty"`
	Location             *Location            `protobuf:"bytes,7,opt,name=Location,json=location,proto3" json:"Location,omitempty"`
	Price                float64              `protobuf:"fixed64,8,opt,name=Price,json=price,proto3" json:"Price,omitempty"`
	Details              *DetailedDescription `protobuf:"bytes,9,opt,name=details,proto3" json:"details,omitempty"`
	Medias               []*Media             `protobuf:"bytes,10,rep,name=Medias,json=medias,proto3" json:"Medias,omitempty"`
	Channel              int32                `protobuf:"varint,11,opt,name=Channel,json=channel,proto3" json:"Channel,omitempty"`
	Deposit              float64              `protobuf:"fixed64,12,opt,name=Deposit,json=deposit,proto3" json:"Deposit,omitempty"`
	AdministrationFee    string               `protobuf:"bytes,13,opt,name=AdministrationFee,json=administrationFee,proto3" json:"AdministrationFee,omitempty"`
	RentFrequency        float64              `protobuf:"fixed64,14,opt,name=RentFrequency,json=rentFrequency,proto3" json:"RentFrequency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListingUpdateRequest) Reset()         { *m = ListingUpdateRequest{} }
func (m *ListingUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*ListingUpdateRequest) ProtoMessage()    {}
func (*ListingUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *ListingUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingUpdateRequest.Unmarshal(m, b)
}
func (m *ListingUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingUpdateRequest.Marshal(b, m, deterministic)
}
func (m *ListingUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingUpdateRequest.Merge(m, src)
}
func (m *ListingUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_ListingUpdateRequest.Size(m)
}
func (m *ListingUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListingUpdateRequest proto.InternalMessageInfo

func (m *ListingUpdateRequest) GetNetworkID() int64 {
	if m != nil {
		return m.NetworkID
	}
	return 0
}

func (m *ListingUpdateRequest) GetBranchID() int64 {
	if m != nil {
		return m.BranchID
	}
	return 0
}

func (m *ListingUpdateRequest) GetAgentRef() string {
	if m != nil {
		return m.AgentRef
	}
	return ""
}

func (m *ListingUpdateRequest) GetPublished() bool {
	if m != nil {
		return m.Published
	}
	return false
}

func (m *ListingUpdateRequest) GetPropertyType() int32 {
	if m != nil {
		return m.PropertyType
	}
	return 0
}

func (m *ListingUpdateRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ListingUpdateRequest) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *ListingUpdateRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ListingUpdateRequest) GetDetails() *DetailedDescription {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *ListingUpdateRequest) GetMedias() []*Media {
	if m != nil {
		return m.Medias
	}
	return nil
}

func (m *ListingUpdateRequest) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *ListingUpdateRequest) GetDeposit() float64 {
	if m != nil {
		return m.Deposit
	}
	return 0
}

func (m *ListingUpdateRequest) GetAdministrationFee() string {
	if m != nil {
		return m.AdministrationFee
	}
	return ""
}

func (m *ListingUpdateRequest) GetRentFrequency() float64 {
	if m != nil {
		return m.RentFrequency
	}
	return 0
}

type ListingDeleteRequest struct {
	NetworkID            int64    `protobuf:"varint,1,opt,name=NetworkID,json=networkID,proto3" json:"NetworkID,omitempty"`
	BranchID             int64    `protobuf:"varint,2,opt,name=BranchID,json=branchID,proto3" json:"BranchID,omitempty"`
	AgentRef             string   `protobuf:"bytes,3,opt,name=AgentRef,json=agentRef,proto3" json:"AgentRef,omitempty"`
	Channel              int32    `protobuf:"varint,4,opt,name=Channel,json=channel,proto3" json:"Channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListingDeleteRequest) Reset()         { *m = ListingDeleteRequest{} }
func (m *ListingDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*ListingDeleteRequest) ProtoMessage()    {}
func (*ListingDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *ListingDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingDeleteRequest.Unmarshal(m, b)
}
func (m *ListingDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingDeleteRequest.Marshal(b, m, deterministic)
}
func (m *ListingDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingDeleteRequest.Merge(m, src)
}
func (m *ListingDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_ListingDeleteRequest.Size(m)
}
func (m *ListingDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListingDeleteRequest proto.InternalMessageInfo

func (m *ListingDeleteRequest) GetNetworkID() int64 {
	if m != nil {
		return m.NetworkID
	}
	return 0
}

func (m *ListingDeleteRequest) GetBranchID() int64 {
	if m != nil {
		return m.BranchID
	}
	return 0
}

func (m *ListingDeleteRequest) GetAgentRef() string {
	if m != nil {
		return m.AgentRef
	}
	return ""
}

func (m *ListingDeleteRequest) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

type ListingResponse struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success              bool     `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	RequestTimestamp     string   `protobuf:"bytes,4,opt,name=request_timestamp,json=requestTimestamp,proto3" json:"request_timestamp,omitempty"`
	ResponseTimestamp    string   `protobuf:"bytes,5,opt,name=response_timestamp,json=responseTimestamp,proto3" json:"response_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListingResponse) Reset()         { *m = ListingResponse{} }
func (m *ListingResponse) String() string { return proto.CompactTextString(m) }
func (*ListingResponse) ProtoMessage()    {}
func (*ListingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *ListingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingResponse.Unmarshal(m, b)
}
func (m *ListingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingResponse.Marshal(b, m, deterministic)
}
func (m *ListingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingResponse.Merge(m, src)
}
func (m *ListingResponse) XXX_Size() int {
	return xxx_messageInfo_ListingResponse.Size(m)
}
func (m *ListingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListingResponse proto.InternalMessageInfo

func (m *ListingResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ListingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListingResponse) GetRequestTimestamp() string {
	if m != nil {
		return m.RequestTimestamp
	}
	return ""
}

func (m *ListingResponse) GetResponseTimestamp() string {
	if m != nil {
		return m.ResponseTimestamp
	}
	return ""
}

type ListingListRequest struct {
	NetworkID            int64    `protobuf:"varint,1,opt,name=NetworkID,json=networkID,proto3" json:"NetworkID,omitempty"`
	BranchID             int64    `protobuf:"varint,2,opt,name=BranchID,json=branchID,proto3" json:"BranchID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListingListRequest) Reset()         { *m = ListingListRequest{} }
func (m *ListingListRequest) String() string { return proto.CompactTextString(m) }
func (*ListingListRequest) ProtoMessage()    {}
func (*ListingListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *ListingListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingListRequest.Unmarshal(m, b)
}
func (m *ListingListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingListRequest.Marshal(b, m, deterministic)
}
func (m *ListingListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingListRequest.Merge(m, src)
}
func (m *ListingListRequest) XXX_Size() int {
	return xxx_messageInfo_ListingListRequest.Size(m)
}
func (m *ListingListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListingListRequest proto.InternalMessageInfo

func (m *ListingListRequest) GetNetworkID() int64 {
	if m != nil {
		return m.NetworkID
	}
	return 0
}

func (m *ListingListRequest) GetBranchID() int64 {
	if m != nil {
		return m.BranchID
	}
	return 0
}

type Listing struct {
	AgentRef             string   `protobuf:"bytes,1,opt,name=agent_ref,json=agentRef,proto3" json:"agent_ref,omitempty"`
	RightmoveId          string   `protobuf:"bytes,2,opt,name=rightmove_id,json=rightmoveId,proto3" json:"rightmove_id,omitempty"`
	UpdateDate           string   `protobuf:"bytes,3,opt,name=update_date,json=updateDate,proto3" json:"update_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Listing) Reset()         { *m = Listing{} }
func (m *Listing) String() string { return proto.CompactTextString(m) }
func (*Listing) ProtoMessage()    {}
func (*Listing) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *Listing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing.Unmarshal(m, b)
}
func (m *Listing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing.Marshal(b, m, deterministic)
}
func (m *Listing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing.Merge(m, src)
}
func (m *Listing) XXX_Size() int {
	return xxx_messageInfo_Listing.Size(m)
}
func (m *Listing) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing.DiscardUnknown(m)
}

var xxx_messageInfo_Listing proto.InternalMessageInfo

func (m *Listing) GetAgentRef() string {
	if m != nil {
		return m.AgentRef
	}
	return ""
}

func (m *Listing) GetRightmoveId() string {
	if m != nil {
		return m.RightmoveId
	}
	return ""
}

func (m *Listing) GetUpdateDate() string {
	if m != nil {
		return m.UpdateDate
	}
	return ""
}

type ListingListResponse struct {
	RequestId            string     `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success              bool       `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	RequestTimestamp     string     `protobuf:"bytes,4,opt,name=request_timestamp,json=requestTimestamp,proto3" json:"request_timestamp,omitempty"`
	ResponseTimestamp    string     `protobuf:"bytes,5,opt,name=response_timestamp,json=responseTimestamp,proto3" json:"response_timestamp,omitempty"`
	Listings             []*Listing `protobuf:"bytes,6,rep,name=listings,proto3" json:"listings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListingListResponse) Reset()         { *m = ListingListResponse{} }
func (m *ListingListResponse) String() string { return proto.CompactTextString(m) }
func (*ListingListResponse) ProtoMessage()    {}
func (*ListingListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *ListingListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingListResponse.Unmarshal(m, b)
}
func (m *ListingListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingListResponse.Marshal(b, m, deterministic)
}
func (m *ListingListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingListResponse.Merge(m, src)
}
func (m *ListingListResponse) XXX_Size() int {
	return xxx_messageInfo_ListingListResponse.Size(m)
}
func (m *ListingListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListingListResponse proto.InternalMessageInfo

func (m *ListingListResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ListingListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListingListResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListingListResponse) GetRequestTimestamp() string {
	if m != nil {
		return m.RequestTimestamp
	}
	return ""
}

func (m *ListingListResponse) GetResponseTimestamp() string {
	if m != nil {
		return m.ResponseTimestamp
	}
	return ""
}

func (m *ListingListResponse) GetListings() []*Listing {
	if m != nil {
		return m.Listings
	}
	return nil
}

func init() {
	proto.RegisterType((*DetailedDescription)(nil), "mashroom.rightmove.DetailedDescription")
	proto.RegisterType((*Media)(nil), "mashroom.rightmove.Media")
	proto.RegisterType((*Coordinates)(nil), "mashroom.rightmove.Coordinates")
	proto.RegisterType((*Location)(nil), "mashroom.rightmove.Location")
	proto.RegisterType((*ListingUpdateRequest)(nil), "mashroom.rightmove.ListingUpdateRequest")
	proto.RegisterType((*ListingDeleteRequest)(nil), "mashroom.rightmove.ListingDeleteRequest")
	proto.RegisterType((*ListingResponse)(nil), "mashroom.rightmove.ListingResponse")
	proto.RegisterType((*ListingListRequest)(nil), "mashroom.rightmove.ListingListRequest")
	proto.RegisterType((*Listing)(nil), "mashroom.rightmove.Listing")
	proto.RegisterType((*ListingListResponse)(nil), "mashroom.rightmove.ListingListResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 891 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xd1, 0x6e, 0x1b, 0x45,
	0x17, 0x96, 0xe3, 0xd8, 0xde, 0x3d, 0xeb, 0xf4, 0x6f, 0xa6, 0xd1, 0xaf, 0x25, 0x2d, 0xd4, 0x2c,
	0x88, 0x5a, 0x82, 0x3a, 0xc2, 0x20, 0xe0, 0xd6, 0x8d, 0x55, 0x14, 0xc9, 0xa4, 0xd1, 0x3a, 0xbd,
	0xa9, 0x84, 0xa2, 0xf1, 0xee, 0xa9, 0x3d, 0x64, 0x77, 0x67, 0x99, 0x99, 0x6d, 0xe5, 0x17, 0xe0,
	0x09, 0xb8, 0xe5, 0x15, 0x78, 0x06, 0x5e, 0x0c, 0x09, 0xcd, 0xec, 0xcc, 0xda, 0x06, 0x2b, 0x54,
	0x42, 0x5c, 0x70, 0x93, 0xf8, 0x7c, 0xe7, 0xf8, 0x9b, 0x39, 0xdf, 0xf9, 0xce, 0xc8, 0xe0, 0xd3,
	0x92, 0x8d, 0x4a, 0xc1, 0x15, 0x27, 0x24, 0xa7, 0x72, 0x25, 0x38, 0xcf, 0x47, 0x82, 0x2d, 0x57,
	0x2a, 0xe7, 0x6f, 0x30, 0xca, 0xe1, 0xc1, 0x14, 0x15, 0x65, 0x19, 0xa6, 0x53, 0x94, 0x89, 0x60,
	0xa5, 0x62, 0xbc, 0x20, 0xa7, 0xe0, 0x3d, 0xc3, 0x54, 0xd7, 0xca, 0xb0, 0x35, 0x68, 0x0d, 0x3b,
	0xb1, 0xb7, 0xb0, 0x31, 0x09, 0xa1, 0x37, 0xaf, 0xf2, 0x9c, 0x8a, 0x75, 0x78, 0x30, 0x68, 0x0d,
	0xfd, 0xb8, 0x27, 0xeb, 0x90, 0x0c, 0x20, 0xd8, 0x22, 0x09, 0xdb, 0x26, 0x1b, 0xa4, 0x1b, 0x28,
	0x9a, 0x40, 0xe7, 0x3b, 0x4c, 0x19, 0x25, 0x8f, 0xc0, 0x37, 0x1f, 0xae, 0xd7, 0x25, 0xda, 0x13,
	0xfc, 0xdc, 0x01, 0xfa, 0x78, 0x93, 0x7d, 0x19, 0xcf, 0xec, 0x19, 0x5e, 0x6e, 0xe3, 0xe8, 0x5b,
	0x08, 0xce, 0x39, 0x17, 0x29, 0x2b, 0xa8, 0x42, 0xa9, 0x4b, 0x67, 0x54, 0x31, 0x55, 0xa5, 0x35,
	0x4f, 0x2b, 0xf6, 0x32, 0x1b, 0xeb, 0x43, 0x66, 0xbc, 0x58, 0xd6, 0xc9, 0x03, 0x93, 0xf4, 0x33,
	0x07, 0x44, 0xbf, 0x1c, 0x80, 0x37, 0xe3, 0x09, 0x35, 0x0d, 0x0f, 0x34, 0x6b, 0x55, 0x28, 0xb1,
	0x3e, 0xe7, 0x96, 0xc9, 0x8f, 0x83, 0x64, 0x03, 0x91, 0x0f, 0x00, 0xae, 0xb8, 0x54, 0x34, 0x33,
	0x05, 0xf5, 0xad, 0xa0, 0x6c, 0x10, 0x32, 0x86, 0x93, 0x2b, 0xc1, 0x4b, 0x14, 0x6a, 0x7d, 0x59,
	0xe5, 0x0b, 0x14, 0x2f, 0xc4, 0x25, 0xcd, 0xd1, 0xaa, 0x70, 0x52, 0xee, 0xc9, 0x69, 0xce, 0xb9,
	0x12, 0x88, 0xca, 0x54, 0x1e, 0xd6, 0x9c, 0xb2, 0x41, 0x74, 0xfe, 0x9a, 0xbf, 0x2d, 0x5e, 0x88,
	0x73, 0xa6, 0xd6, 0x61, 0xa7, 0xce, 0xab, 0x06, 0x21, 0x93, 0x1d, 0x2d, 0xc2, 0xee, 0xa0, 0x35,
	0x0c, 0xc6, 0x8f, 0x47, 0x7f, 0x9d, 0xf3, 0x68, 0xab, 0x4c, 0xb7, 0xb5, 0xd1, 0x2f, 0x84, 0xde,
	0x24, 0x4d, 0x05, 0x4a, 0x19, 0xf6, 0xea, 0x69, 0xd2, 0x3a, 0x8c, 0x7e, 0x3e, 0x84, 0x93, 0x19,
	0x93, 0x8a, 0x15, 0xcb, 0x97, 0x65, 0x4a, 0x15, 0xc6, 0xf8, 0x63, 0x85, 0x52, 0x69, 0x59, 0x2f,
	0x51, 0xbd, 0xe5, 0xe2, 0xf6, 0x62, 0x6a, 0x94, 0x6a, 0xc7, 0x7e, 0xe1, 0x00, 0x63, 0x1d, 0x41,
	0x8b, 0x64, 0x75, 0x31, 0x35, 0x2a, 0xb5, 0x63, 0x6f, 0x61, 0x63, 0x9d, 0x9b, 0x2c, 0xb1, 0x50,
	0x31, 0xbe, 0xb6, 0xba, 0x78, 0xd4, 0xc6, 0x9a, 0xf5, 0xaa, 0x5a, 0x64, 0x4c, 0xae, 0x30, 0x35,
	0x52, 0x78, 0xb1, 0x5f, 0x3a, 0x80, 0x44, 0xd0, 0x77, 0xea, 0x1a, 0xcb, 0x74, 0x8c, 0x65, 0xfa,
	0xe5, 0x16, 0x46, 0xfe, 0x0f, 0xdd, 0xb9, 0xa2, 0xaa, 0xaa, 0x85, 0xe8, 0xc4, 0x5d, 0x69, 0x22,
	0xf2, 0xcd, 0x66, 0xce, 0xa6, 0xc7, 0x60, 0xfc, 0x68, 0x9f, 0x44, 0xae, 0x26, 0xf6, 0x32, 0xe7,
	0x8a, 0x13, 0xe8, 0x5c, 0x09, 0x96, 0x60, 0xe8, 0x19, 0xf3, 0x74, 0x4a, 0x1d, 0x90, 0x09, 0xf4,
	0x52, 0xb3, 0x33, 0x32, 0xf4, 0x0d, 0xdd, 0x93, 0x7d, 0x74, 0x7b, 0xd6, 0x2a, 0x76, 0xdf, 0x23,
	0x9f, 0x43, 0xd7, 0x18, 0x5c, 0x86, 0x30, 0x68, 0x0f, 0x83, 0xf1, 0x7b, 0xfb, 0x18, 0x4c, 0x45,
	0xdc, 0x35, 0xce, 0x37, 0x83, 0x3a, 0x5f, 0xd1, 0xa2, 0xc0, 0x2c, 0x0c, 0x4c, 0x7b, 0xbd, 0xa4,
	0x0e, 0x75, 0x66, 0x8a, 0x25, 0x97, 0x4c, 0x85, 0x7d, 0x73, 0xcf, 0x5e, 0x5a, 0x87, 0xe4, 0x33,
	0x38, 0x9e, 0xa4, 0x39, 0x2b, 0x98, 0x54, 0xc2, 0x74, 0xf4, 0x1c, 0x31, 0x3c, 0x32, 0xc2, 0x1f,
	0xd3, 0x3f, 0x27, 0xc8, 0xc7, 0x70, 0x14, 0x63, 0xa1, 0x9e, 0x0b, 0x3d, 0xe7, 0x22, 0x59, 0x87,
	0xf7, 0x0c, 0xdb, 0x91, 0xd8, 0x06, 0xa3, 0x9f, 0x5a, 0x8d, 0x2d, 0xa6, 0x98, 0xe1, 0xbf, 0x6d,
	0x8b, 0xad, 0xb6, 0x0f, 0x77, 0xda, 0x8e, 0x7e, 0x6b, 0xc1, 0xff, 0xec, 0x45, 0x62, 0x94, 0x25,
	0x2f, 0x24, 0x92, 0xf7, 0x01, 0x44, 0x7d, 0x9d, 0x1b, 0x96, 0xda, 0x2d, 0xf6, 0x2d, 0x72, 0x91,
	0x6a, 0xb2, 0x1c, 0xa5, 0xa4, 0x4b, 0xb7, 0xc0, 0x2e, 0xd4, 0x19, 0x59, 0x25, 0x89, 0x5e, 0x83,
	0xb6, 0xf1, 0x9e, 0x0b, 0xc9, 0xa7, 0x70, 0xec, 0x28, 0x15, 0xcb, 0x51, 0x2a, 0x9a, 0x97, 0x76,
	0x55, 0xef, 0xdb, 0xc4, 0xb5, 0xc3, 0xc9, 0x53, 0x20, 0xc2, 0xde, 0x65, 0xab, 0xba, 0x5e, 0xdc,
	0x63, 0x97, 0x69, 0xca, 0xa3, 0x4b, 0x20, 0xb6, 0x03, 0xfd, 0xef, 0x1f, 0x0b, 0x19, 0xfd, 0x00,
	0x3d, 0xcb, 0x47, 0x1e, 0x82, 0x6f, 0x34, 0xbc, 0x11, 0xf8, 0xda, 0x0a, 0xb1, 0x11, 0xf5, 0x43,
	0xe8, 0x37, 0x36, 0xd3, 0x42, 0xd5, 0x62, 0x04, 0x0d, 0x76, 0x91, 0x92, 0xc7, 0x10, 0x54, 0x66,
	0xeb, 0x6f, 0xf4, 0x1f, 0x3b, 0x16, 0xa8, 0xa1, 0x29, 0x55, 0x18, 0xfd, 0xde, 0x82, 0x07, 0x3b,
	0x97, 0xff, 0x4f, 0x8e, 0x80, 0x7c, 0x0d, 0x5e, 0x56, 0x77, 0xa1, 0x9f, 0x0d, 0xbd, 0x8b, 0x0f,
	0xf7, 0x3e, 0x0e, 0xd6, 0x68, 0x4d, 0xf1, 0xf8, 0xd7, 0x03, 0xb8, 0x1f, 0xbb, 0xfc, 0x1c, 0xc5,
	0x1b, 0xfd, 0x34, 0x7c, 0x0f, 0xfd, 0x39, 0x16, 0xa9, 0x7b, 0xaa, 0xc8, 0xf0, 0x0e, 0xae, 0x9d,
	0x47, 0xf5, 0xf4, 0xa3, 0xbb, 0x4e, 0x75, 0xda, 0xde, 0xc0, 0xbd, 0x7a, 0xe7, 0xde, 0xe9, 0x80,
	0x9d, 0xf5, 0x7c, 0xb7, 0x03, 0x5e, 0x6d, 0x0c, 0xf4, 0xc9, 0x1d, 0xf5, 0x5b, 0x6e, 0x3d, 0x7d,
	0xf2, 0xb7, 0x75, 0x35, 0xf7, 0xb3, 0xaf, 0x5e, 0x7d, 0xb9, 0x64, 0x2a, 0xa3, 0x8b, 0x11, 0xbf,
	0x55, 0xf4, 0xa9, 0xe4, 0x59, 0xa5, 0x5f, 0x1e, 0x39, 0x4a, 0x78, 0x7e, 0xe6, 0x38, 0xce, 0x16,
	0x34, 0xb9, 0xc5, 0x22, 0x3d, 0x6b, 0xb8, 0x16, 0x5d, 0xf3, 0xeb, 0xe5, 0x8b, 0x3f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xe9, 0xab, 0x64, 0x45, 0xca, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RightmoveServiceClient is the client API for RightmoveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RightmoveServiceClient interface {
	//    rpc BranchUpdate (BranchUpdateRequest) returns (BranchUpdateResponse);
	SendProperty(ctx context.Context, in *ListingUpdateRequest, opts ...grpc.CallOption) (*ListingResponse, error)
	DeleteProperty(ctx context.Context, in *ListingDeleteRequest, opts ...grpc.CallOption) (*ListingResponse, error)
	Listing(ctx context.Context, in *ListingListRequest, opts ...grpc.CallOption) (*ListingListResponse, error)
}

type rightmoveServiceClient struct {
	cc *grpc.ClientConn
}

func NewRightmoveServiceClient(cc *grpc.ClientConn) RightmoveServiceClient {
	return &rightmoveServiceClient{cc}
}

func (c *rightmoveServiceClient) SendProperty(ctx context.Context, in *ListingUpdateRequest, opts ...grpc.CallOption) (*ListingResponse, error) {
	out := new(ListingResponse)
	err := c.cc.Invoke(ctx, "/mashroom.rightmove.RightmoveService/SendProperty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rightmoveServiceClient) DeleteProperty(ctx context.Context, in *ListingDeleteRequest, opts ...grpc.CallOption) (*ListingResponse, error) {
	out := new(ListingResponse)
	err := c.cc.Invoke(ctx, "/mashroom.rightmove.RightmoveService/DeleteProperty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rightmoveServiceClient) Listing(ctx context.Context, in *ListingListRequest, opts ...grpc.CallOption) (*ListingListResponse, error) {
	out := new(ListingListResponse)
	err := c.cc.Invoke(ctx, "/mashroom.rightmove.RightmoveService/Listing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RightmoveServiceServer is the server API for RightmoveService service.
type RightmoveServiceServer interface {
	//    rpc BranchUpdate (BranchUpdateRequest) returns (BranchUpdateResponse);
	SendProperty(context.Context, *ListingUpdateRequest) (*ListingResponse, error)
	DeleteProperty(context.Context, *ListingDeleteRequest) (*ListingResponse, error)
	Listing(context.Context, *ListingListRequest) (*ListingListResponse, error)
}

func RegisterRightmoveServiceServer(s *grpc.Server, srv RightmoveServiceServer) {
	s.RegisterService(&_RightmoveService_serviceDesc, srv)
}

func _RightmoveService_SendProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListingUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RightmoveServiceServer).SendProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mashroom.rightmove.RightmoveService/SendProperty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RightmoveServiceServer).SendProperty(ctx, req.(*ListingUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RightmoveService_DeleteProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListingDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RightmoveServiceServer).DeleteProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mashroom.rightmove.RightmoveService/DeleteProperty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RightmoveServiceServer).DeleteProperty(ctx, req.(*ListingDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RightmoveService_Listing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListingListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RightmoveServiceServer).Listing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mashroom.rightmove.RightmoveService/Listing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RightmoveServiceServer).Listing(ctx, req.(*ListingListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RightmoveService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mashroom.rightmove.RightmoveService",
	HandlerType: (*RightmoveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendProperty",
			Handler:    _RightmoveService_SendProperty_Handler,
		},
		{
			MethodName: "DeleteProperty",
			Handler:    _RightmoveService_DeleteProperty_Handler,
		},
		{
			MethodName: "Listing",
			Handler:    _RightmoveService_Listing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
