// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package cardpayment

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PaymentByCardRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentByCardRequest) Reset()         { *m = PaymentByCardRequest{} }
func (m *PaymentByCardRequest) String() string { return proto.CompactTextString(m) }
func (*PaymentByCardRequest) ProtoMessage()    {}
func (*PaymentByCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *PaymentByCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentByCardRequest.Unmarshal(m, b)
}
func (m *PaymentByCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentByCardRequest.Marshal(b, m, deterministic)
}
func (m *PaymentByCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentByCardRequest.Merge(m, src)
}
func (m *PaymentByCardRequest) XXX_Size() int {
	return xxx_messageInfo_PaymentByCardRequest.Size(m)
}
func (m *PaymentByCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentByCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentByCardRequest proto.InternalMessageInfo

func (m *PaymentByCardRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PaymentByCardRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type PaymentByCardResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentByCardResponse) Reset()         { *m = PaymentByCardResponse{} }
func (m *PaymentByCardResponse) String() string { return proto.CompactTextString(m) }
func (*PaymentByCardResponse) ProtoMessage()    {}
func (*PaymentByCardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *PaymentByCardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentByCardResponse.Unmarshal(m, b)
}
func (m *PaymentByCardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentByCardResponse.Marshal(b, m, deterministic)
}
func (m *PaymentByCardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentByCardResponse.Merge(m, src)
}
func (m *PaymentByCardResponse) XXX_Size() int {
	return xxx_messageInfo_PaymentByCardResponse.Size(m)
}
func (m *PaymentByCardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentByCardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentByCardResponse proto.InternalMessageInfo

func (m *PaymentByCardResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PaymentByCardResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*PaymentByCardRequest)(nil), "mashroom.cardpayment.PaymentByCardRequest")
	proto.RegisterType((*PaymentByCardResponse)(nil), "mashroom.cardpayment.PaymentByCardResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xbf, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0x89, 0xe2, 0x69, 0x16, 0x6c, 0x96, 0x28, 0xc1, 0xea, 0xb8, 0xea, 0x50, 0xdc, 0x80,
	0x82, 0x58, 0xdf, 0xd9, 0xd9, 0xc8, 0xda, 0xd9, 0x4d, 0x36, 0xc3, 0x5d, 0xc8, 0xed, 0x4e, 0xdc,
	0x99, 0x08, 0xd7, 0xf8, 0xb7, 0x8b, 0x89, 0xc1, 0x1f, 0xa4, 0xb0, 0xdb, 0x8f, 0x1d, 0xbe, 0x79,
	0x6f, 0x54, 0x0a, 0x6d, 0x6d, 0xda, 0x48, 0x42, 0x3a, 0xf3, 0xc0, 0xdb, 0x48, 0xe4, 0x8d, 0x83,
	0x58, 0xb5, 0xb0, 0xf7, 0x18, 0x64, 0xf1, 0xa0, 0xb2, 0xa7, 0xe1, 0xb9, 0xda, 0xaf, 0x21, 0x56,
	0x16, 0x5f, 0x3b, 0x64, 0xd1, 0x99, 0x3a, 0x12, 0x6a, 0x30, 0xe4, 0xc9, 0x3c, 0x59, 0xa6, 0x76,
	0x00, 0x7d, 0xae, 0x66, 0xe0, 0xa9, 0x0b, 0x92, 0x1f, 0xcc, 0x93, 0xe5, 0xa1, 0xfd, 0xa2, 0xc5,
	0xa3, 0x3a, 0xfb, 0x63, 0xe1, 0x96, 0x02, 0xa3, 0xce, 0xd5, 0x31, 0x77, 0xce, 0x21, 0x73, 0x2f,
	0x3a, 0xb1, 0x23, 0x7e, 0xfe, 0x78, 0x64, 0x86, 0x0d, 0xf6, 0xae, 0xd4, 0x8e, 0x78, 0xf3, 0xae,
	0xf4, 0xfa, 0x3b, 0xe1, 0x33, 0xc6, 0xb7, 0xda, 0xa1, 0xde, 0xaa, 0xd3, 0x5f, 0x2b, 0xf4, 0xa5,
	0x99, 0x2a, 0x64, 0xa6, 0xda, 0x5c, 0x5c, 0xfd, 0x6b, 0x76, 0xc8, 0xbc, 0xba, 0x7f, 0xb9, 0xdb,
	0xd4, 0xb2, 0x83, 0xd2, 0x50, 0x23, 0x70, 0xcd, 0xb4, 0xeb, 0xa4, 0xa6, 0xc0, 0xc6, 0x91, 0x2f,
	0x46, 0x4f, 0x51, 0x82, 0x6b, 0x30, 0x54, 0xc5, 0x0f, 0x5f, 0x39, 0xeb, 0x2f, 0x7d, 0xfb, 0x11,
	0x00, 0x00, 0xff, 0xff, 0xb0, 0x02, 0x35, 0xdc, 0x76, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CardpaymentServiceClient is the client API for CardpaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CardpaymentServiceClient interface {
	PaymentByCard(ctx context.Context, in *PaymentByCardRequest, opts ...grpc.CallOption) (*PaymentByCardResponse, error)
}

type cardpaymentServiceClient struct {
	cc *grpc.ClientConn
}

func NewCardpaymentServiceClient(cc *grpc.ClientConn) CardpaymentServiceClient {
	return &cardpaymentServiceClient{cc}
}

func (c *cardpaymentServiceClient) PaymentByCard(ctx context.Context, in *PaymentByCardRequest, opts ...grpc.CallOption) (*PaymentByCardResponse, error) {
	out := new(PaymentByCardResponse)
	err := c.cc.Invoke(ctx, "/mashroom.cardpayment.CardpaymentService/PaymentByCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardpaymentServiceServer is the server API for CardpaymentService service.
type CardpaymentServiceServer interface {
	PaymentByCard(context.Context, *PaymentByCardRequest) (*PaymentByCardResponse, error)
}

func RegisterCardpaymentServiceServer(s *grpc.Server, srv CardpaymentServiceServer) {
	s.RegisterService(&_CardpaymentService_serviceDesc, srv)
}

func _CardpaymentService_PaymentByCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentByCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardpaymentServiceServer).PaymentByCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mashroom.cardpayment.CardpaymentService/PaymentByCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardpaymentServiceServer).PaymentByCard(ctx, req.(*PaymentByCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CardpaymentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mashroom.cardpayment.CardpaymentService",
	HandlerType: (*CardpaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PaymentByCard",
			Handler:    _CardpaymentService_PaymentByCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
